#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/device-discovery
CONF_FILE=/etc/config/device-discovery

start_service() {
	local enabled interface network
	
	config_load device-discovery
	config_get enabled main enabled 0
	config_get interface main interface "br-lan"
	config_get network main network "192.168.10.0/24"
	
	[ "$enabled" = "1" ] || return 0
	
	procd_open_instance
	procd_set_param command $PROG -i "$interface" -n "$network" -m
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	killall device-discovery 2>/dev/null
}

reload_service() {
	stop
	start
}